### ISSUE TITLE
Errors

### ISSUE THREAD

**Issue by ValbertonHere** [atacms/wot-model-converter#3]
I try to convert a primitive and i get this

Traceback (most recent call last):
  File "convert-primitive.py", line 180, in <module>
    tmp = model_reader.read(primitives_f, visual_f)
  File "D:\UGV_Mod\GraphX\wot-model-converter-master\wot\ModelReader.py", line 150, in read
    vertices = self.readVertices(sections[vertices_name]['data'])
KeyError: 'chassis_R_Shape.vertices'

Can you help me and tell, what's the problem?

Python 3.8.10

**Comment by atacms** [comment]
maybe there's a new format variant. Where did you get the model file from?

**Comment by ValbertonHere** [comment]
vehicles\german\G89_Leopard1\

**Comment by atacms** [comment]
[https://b.radikal.ru/b07/2105/dd/7caac63899ea.jpg](url)
idk, it's fine on python2.7
I can't test it on my 3.8 python there's a certain urllib bug preventing me from installing dateutil through a proxy.

perhaps you can try using that executable release package V2.1 instead, or use pythong2.7x

**Comment by ValbertonHere** [comment]
Fine, i'll try it
