### ISSUE TITLE
1030B的3D Hull导出dae报错

### ISSUE THREAD

**Issue by aptx2018** [atacms/wot-model-converter#4]
\S11_Strv_103B_MD22_III_3DSt\normal\lod0\Hull.primitives_processed
position vector count:34486
position vector count:17751
position vector count:3025
skinned renderSet
\# of primitiveGroups in this set: 2
[1.0, 0.0, 0.0, 0.0, -0.0, -1.0, -0.0, 0.0, 0.0, 0.0, 1.0, 0.0, 0, 0, 0, 1]
number of bone matrices retrieved: 1
Traceback (most recent call last):
  File "convert-primitive.py", line 178, in <module>
    model_writer.write(tmp, filename_obj, filename_mtl)
  File "D:\BWindie2.1\bigworld\res\WOT\scenes\wot-model-converter-master_new_PC\wot\ColladaModelWriter.py", line 314, in write
    for [idxW, w] in enumerate(lstWeight):
TypeError: 'NoneType' object is not iterable

**Comment by atacms** [comment]
嗯，谢谢回报。
是在处理一个文件里同时混杂skinned和非skinned的多个renderSet时出现的问题。快修好了。

**Comment by atacms** [comment]
fixed.
